### ISSUE TITLE
Ignore tags when retrieving the latest version

### ISSUE THREAD

**Issue by kayman-mk** [mrooding/gitlab-semantic-versioning#10]
If I have more than one tag on a commit `git describe --tags` might return the wrong tag. What about adding an environment variable with tag names to be excluded? These names could be passed to `git describe` with `--exclude latest --exclude stable`

What do you think?

**Comment by kayman-mk** [comment]
Another option: `git tag --contains ${CI_COMMIT_ID}` to retrieve all tags and then filter the semantic version tag. But you need a `git describe --tags --always --match 'the found tag'` in case no version tag is found.

**Comment by mrooding** [comment]
Hey @kayman-mk I think I'd prefer the second option but given the fallback that you need if no version tag is found, I think extracting the right tag deserves its own script. Then we can hide the complexity within the script instead of the pipeline stage definition. Would you like to take a stab at it?

**Comment by kayman-mk** [comment]
@mrooding The second option is also my favorite which I have already implemented in a private fork. I will create a PR.
